package it.unibo.elementsduo.model.collisions.core.impl;

import java.util.ArrayList;
import java.util.List;

import it.unibo.elementsduo.model.collisions.commands.api.CollisionCommand;

/**
 * Represents a collection of collision responses generated by different
 * handlers.
 * 
 * <p>
 * The {@code CollisionResponse} groups and executes both physics-related and
 * logic-related collision commands in a specific order.
 */
public final class CollisionResponse {

    /** The list of physics-related collision commands. */
    private final List<CollisionCommand> physicsCommands;

    /** The list of logic-related collision commands. */
    private final List<CollisionCommand> logicCommands;

    /**
     * Creates a new {@code CollisionResponse} containing the given command lists.
     *
     * @param physicsCommands the list of physics-related commands
     * @param logicCommands   the list of logic-related commands
     */
    private CollisionResponse(final List<CollisionCommand> physicsCommands,
            final List<CollisionCommand> logicCommands) {
        this.physicsCommands = List.copyOf(physicsCommands);
        this.logicCommands = List.copyOf(logicCommands);
    }

    /**
     * Executes all registered collision commands in order.
     * 
     * <p>
     * Physics commands are executed first, followed by logic commands.
     */
    public void execute() {
        this.physicsCommands.forEach(CollisionCommand::execute);
        this.logicCommands.forEach(CollisionCommand::execute);
    }

    /**
     * Builder class for constructing {@link CollisionResponse} instances.
     * 
     * <p>
     * Use this builder to collect physics and logic commands before creating the
     * final response object.
     */
    public static final class Builder {

        private final List<CollisionCommand> physicsCommands = new ArrayList<>();
        private final List<CollisionCommand> logicCommands = new ArrayList<>();

        /**
         * Adds a logic-related command to the response.
         * 
         * <p>
         * This method is final to ensure consistent builder behavior.
         *
         * @param command the logic command to add
         */
        public final void addLogicCommand(CollisionCommand command) {
            this.logicCommands.add(command);
        }

        /**
         * Adds a physics-related command to the response.
         * 
         * <p>
         * This method is final to ensure consistent builder behavior.
         *
         * @param command the physics command to add
         */
        public final void addPhysicsCommand(CollisionCommand command) {
            this.physicsCommands.add(command);
        }

        /**
         * Builds a new {@link CollisionResponse} instance containing all
         * accumulated commands.
         *
         * @return a new {@code CollisionResponse} instance
         */
        public CollisionResponse build() {
            return new CollisionResponse(this.physicsCommands, this.logicCommands);
        }
    }
}
